// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/transfer": {
    params: {};
  };
  "/setting": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/transfer" | "/setting";
  };
  "routes/sidebar.tsx": {
    id: "routes/sidebar";
    page: "/" | "/transfer" | "/setting";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/transfer.tsx": {
    id: "routes/transfer";
    page: "/transfer";
  };
  "routes/setting.tsx": {
    id: "routes/setting";
    page: "/setting";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/sidebar": typeof import("./src/routes/sidebar.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/transfer": typeof import("./src/routes/transfer.tsx");
  "routes/setting": typeof import("./src/routes/setting.tsx");
};